[vars]
author = "Madhav Khandhar"
title = "Blog by Madhav"
first_name = "Madhav"
last_name = "Khandhar"
linkedin = "https://www.linkedin.com/in/madhav-khandhar/"
github = "https://github.com/Mvk122"
sitesy = "https://github.com/Mvk122/sitesy"
